name: Request PipelineRundeck

on:
  push:
    branches:
      - main

jobs:
  request-pipeline:
    uses: Ll2223/ga-pipelines/.github/workflows/PipelineRundeck.yml@main
    with:
      hml: 'true'
      hml_1-5: 'true'
    secrets: inherit

#
